# Loading libraries

In [ ]:
import pandas as pd
import numpy as np

# Loading datasets

In [103]:
pop_data_missense_annovar = pd.read_csv("/Users/ricardo/Desktop/MECD/2ndYear/Thesis/datasets_final/pop_data_missense_annovar.csv",
                                        sep="\t")

,User_input,Polyphen2_HVAR_pred,Polyphen2_HDIV_pred,Uniprot_aapos_Polyphen2,CADD_phred,LoFtool_score,RVIS_percentile,RVIS,GDI,GDI_Phred,...,phastCons100way_vertebrate,phastCons100way_vertebrate_rankscore,phastCons30way_mammalian,phastCons30way_mammalian_rankscore,SiPhy_29way_logOdds,SiPhy_29way_logOdds_rankscore,InterVar_automated,regsnp_fpr,regsnp_disease,regsnp_splicing_site
0,1:69134:A:G,B,B,15,10.150,NaN,NaN,NaN,113.16669,2.31572,...,0.000,0.064,0.957,0.428,8.509,0.324,Likely_benign,NaN,NaN,NaN
1,1:69149:T:A,D,D,20,23.000,NaN,NaN,NaN,113.16669,2.31572,...,0.001,0.138,0.868,0.360,5.811,0.177,Likely_benign,NaN,NaN,NaN
2,1:69162:T:G,P,P,24,11.950,NaN,NaN,NaN,113.16669,2.31572,...,0.000,0.064,0.982,0.484,4.848,0.129,Likely_benign,NaN,NaN,NaN
3,1:69200:T:C,P,P,37,13.030,NaN,NaN,NaN,113.16669,2.31572,...,0.000,0.064,0.991,0.532,5.811,0.177,Likely_benign,NaN,NaN,NaN
4,1:69224:A:T,D,D,45,23.200,NaN,NaN,NaN,113.16669,2.31572,...,0.004,0.166,0.575,0.285,8.509,0.324,Uncertain_significance,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
706490,Y:23229667:C:A,D/P/P/D/P/P/D,P/D/P/D/P/D/D,190,24.500,NaN,NaN,NaN,NaN,NaN,...,1.000,0.716,0.969,0.448,NaN,NaN,Uncertain_significance,NaN,NaN,NaN
706491,Y:24362373:G:C,NaN,NaN,NaN,6.758,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
706492,Y:24362375:C:G,NaN,NaN,NaN,9.428,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
706493,Y:24864466:T:A,P/P/B/P,P/P/B/P,"220,220,269,269",20.100,NaN,NaN,NaN,NaN,NaN,...,1.000,0.716,0.569,0.284,NaN,NaN,Uncertain_significance,NaN,NaN,NaN
706494,Y:24864482:A:G,B,B,"226,226,275,395",11.470,NaN,NaN,NaN,NaN,NaN,...,1.000,0.716,0.479,0.269,NaN,NaN,Uncertain_significance,NaN,NaN,NaN

In [114]:
final_clinpgx_processed_dataset_annovar = pd.read_csv("/Users/ricardo/Desktop/MECD/2ndYear/Thesis/datasets_final/final_clinpgx_processed_dataset_Annovar.hg38_multianno.txt",
                                                  sep="\t")


final_clinpgx_processed_dataset_annovar = final_clinpgx_processed_dataset_annovar.drop(columns=final_clinpgx_processed_dataset_annovar.iloc[:,174:202].columns, axis=1)
final_clinpgx_processed_dataset_annovar = final_clinpgx_processed_dataset_annovar.drop(columns="Otherinfo")

final_clinpgx_processed_dataset_annovar = final_clinpgx_processed_dataset_annovar.drop_duplicates()

final_clinpgx_processed_dataset_annovar['User_input'] = (
    final_clinpgx_processed_dataset_annovar['Chr'].astype(str) + ":" +
    final_clinpgx_processed_dataset_annovar['Start'].astype(str) + ":" +
    final_clinpgx_processed_dataset_annovar['Ref'].astype(str) + ":" +
    final_clinpgx_processed_dataset_annovar['Alt'].astype(str)
)

final_clinpgx_processed_dataset_annovar.replace(".", np.nan, inplace=True)
final_clinpgx_processed_dataset_annovar.replace("NA", np.nan, inplace=True)

final_clinpgx_processed_dataset_annovar.drop(columns=["Chr", "Start", "End", "Ref", "Alt"], inplace=True)
final_clinpgx_processed_dataset_annovar = final_clinpgx_processed_dataset_annovar[final_clinpgx_processed_dataset_annovar.columns[-1:].tolist() + final_clinpgx_processed_dataset_annovar.columns[:-1].tolist()]

,User_input,Func.refGene,Gene.refGene,GeneDetail.refGene,ExonicFunc.refGene,AAChange.refGene,CLNALLELEID,CLNDN,CLNDISDB,CLNREVSTAT,...,GTEx_V8_eQTL_gene,GTEx_V8_eQTL_tissue,GTEx_V8_sQTL_gene,GTEx_V8_sQTL_tissue,eQTLGen_snp_id,avsnp151,InterVar_automated,regsnp_fpr,regsnp_disease,regsnp_splicing_site
0,2:162015288:C:T,intronic,DPP4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,rs2909451,NaN,NaN,NaN,NaN
1,11:17386478:A:G,UTR3,KCNJ11,NM_001166290:c.*441T>C;NM_000525:c.*441T>C;NM_...,NaN,NaN,326654,Maturity-onset_diabetes_of_the_young_type_13|T...,"MONDO:MONDO:0014589,MedGen:C4225365,OMIM:61632...","criteria_provided,_conflicting_classifications",...,NaN,NaN,NaN,NaN,NaN,rs2285676,Benign,NaN,NaN,NaN
2,11:2825839:T:G,intronic,KCNQ1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,rs163184,NaN,NaN,NaN,NaN
3,2:162029379:A:G,intronic,DPP4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,rs4664443,NaN,NaN,NaN,NaN
4,10:94942290:C:T,exonic,CYP2C9,NaN,nonsynonymous SNV,CYP2C9:NM_000771:exon3:c.C430T:p.R144C,23448,Flurbiprofen_response|Piroxicam_response|Lesin...,MedGen:CN258139|MedGen:CN258188|MedGen:CN24878...,"criteria_provided,_multiple_submitters,_no_con...",...,HELLS|ACSM6|HELLS|HELLS|CYP2C8,Nerve_Tibial|Nerve_Tibial|Skin_Not_Sun_Exposed...,PDLIM1,Artery_Tibial,rs1799853,rs1799853,Benign,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,8:18400344:T:C,exonic,NAT2,NaN,nonsynonymous SNV,NAT2:NM_000015:exon2:c.T341C:p.I114T,15762,NAT2-related_disorder|Slow_acetylator_due_to_N...,".|MONDO:MONDO:0009472,MedGen:C0878587,OMIM:243400",no_assertion_criteria_provided,...,NaN,NaN,NaN,NaN,rs1801280,rs1801280,Benign,NaN,NaN,NaN
10714,8:18400194:G:A,exonic,NAT2,NaN,nonsynonymous SNV,NAT2:NM_000015:exon2:c.G191A:p.R64Q,15765,Slow_acetylator_due_to_N-acetyltransferase_enz...,"MONDO:MONDO:0009472,MedGen:C0878587,OMIM:243400|.",no_assertion_criteria_provided,...,NaN,NaN,NaN,NaN,NaN,rs1801279,Likely benign,NaN,NaN,NaN
10768,1:97740411:ATGA:-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10776,13:48037796:GAGTCG:-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10784,6:18130762:C:T,exonic,TPMT,NaN,nonsynonymous SNV,"TPMT:NM_001346818:exon8:c.G599A:p.R200H,TPMT:N...",27765,Thiopurine_S-methyltransferase_deficiency,"MONDO:MONDO:0012503,MedGen:C0342801,OMIM:610460",no_assertion_criteria_provided,...,NaN,NaN,NaN,NaN,NaN,rs56161402,Likely benign,NaN,NaN,NaN

# Data processing

In [115]:
pop_data_missense_annovar_cols = pop_data_missense_annovar.columns.to_list()
final_clinpgx_processed_dataset_annovar_cols = final_clinpgx_processed_dataset_annovar.columns.to_list()

In [ ]:
common_cols = pop_data_missense_annovar.columns.intersection(
    final_clinpgx_processed_dataset_annovar.columns
    ).to_list()

In [118]:
def subset_for_common(df):
  df = df[common_cols]
  return df


pop_data_missense_annovar = subset_for_common(pop_data_missense_annovar)
final_clinpgx_processed_dataset_annovar = subset_for_common(final_clinpgx_processed_dataset_annovar)

In [123]:
annovar_dataset = pd.concat([pop_data_missense_annovar, final_clinpgx_processed_dataset_annovar], axis=0).reset_index(drop=True)

In [161]:
annovar_dataset.drop_duplicates(inplace=True)

,User_input,Polyphen2_HVAR_pred,Polyphen2_HDIV_pred,CADD_phred,CLNSIG,SIFT_score,SIFT_converted_rankscore,SIFT_pred,SIFT4G_score,SIFT4G_converted_rankscore,...,phyloP100way_vertebrate,phyloP100way_vertebrate_rankscore,phastCons100way_vertebrate,phastCons100way_vertebrate_rankscore,SiPhy_29way_logOdds,SiPhy_29way_logOdds_rankscore,InterVar_automated,regsnp_fpr,regsnp_disease,regsnp_splicing_site
0,1:69134:A:G,B,B,10.15,Likely_benign,0.129,0.269,T,0.107,0.377,...,0.405,0.207,0.0,0.064,8.509,0.324,Likely_benign,NaN,NaN,NaN
1,1:69149:T:A,D,D,23.0,NaN,0.001,0.785,D,0.001,0.834,...,1.085,0.305,0.001,0.138,5.811,0.177,Likely_benign,NaN,NaN,NaN
2,1:69162:T:G,P,P,11.95,NaN,0.005,0.632,D,0.081,0.417,...,-0.902,0.042,0.0,0.064,4.848,0.129,Likely_benign,NaN,NaN,NaN
3,1:69200:T:C,P,P,13.03,NaN,0.014,0.532,D,0.0,0.928,...,0.178,0.166,0.0,0.064,5.811,0.177,Likely_benign,NaN,NaN,NaN
4,1:69224:A:T,D,D,23.2,NaN,0.0,0.913,D,0.0,0.928,...,2.043,0.409,0.004,0.166,8.509,0.324,Uncertain_significance,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708724,8:18400344:T:C,P,B,20.7,Benign|drug_response,0.048,0.40068,D,0.043,0.49942,...,3.857000,0.55682,0.958000,0.33488,4.753,0.12442,Benign,NaN,NaN,NaN
708725,8:18400194:G:A,D,D,23.3,Likely_benign|drug_response,0.009,0.57480,D,0.0,0.92824,...,4.275000,0.58723,0.778000,0.29449,3.670,0.07805,Likely benign,NaN,NaN,NaN
708726,1:97740411:ATGA:-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
708727,13:48037796:GAGTCG:-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
708728,6:18130762:C:T,B,B,0.075,drug_response,0.532,0.06980,T,0.304,0.20100,...,-1.029000,0.03696,0.000000,0.06391,0.923,0.01235,Likely benign,NaN,NaN,NaN

In [ ]:
duplicates = annovar_dataset['User_input'].value_counts()
duplicates = duplicates[duplicates > 1]
duplicates = duplicates.index.tolist()

In [166]:
def deduplicate(df):
  df.update(df.groupby('User_input').ffill())
  df_deduped = df.drop_duplicates(subset=['User_input'], keep='last')
  return df_deduped

annovar_dataset_deduplicate = deduplicate(annovar_dataset)

In [179]:
annovar_dataset_deduplicate.to_csv("/Users/ricardo/Desktop/MECD/2ndYear/Thesis/datasets_final/annovar_dataset_final.csv", index=False)